const test=require("node:test"),assert=require("node:assert/strict"),Audio=require("../js/city-shuttle-audio.js");
class Param{constructor(value=0){this.value=value;}setTargetAtTime(value){this.value=value;}}
class Node{constructor(){this.gain=new Param(1);this.frequency=new Param();this.playbackRate=new Param(1);this.positionX=new Param();this.positionY=new Param();this.positionZ=new Param();this.threshold=new Param();this.knee=new Param();this.ratio=new Param();this.connected=false;this.started=false;this.stopped=false;}connect(){this.connected=true;}disconnect(){this.connected=false;}start(){this.started=true;}stop(){this.stopped=true;}}
class Context{constructor(){this.currentTime=0;this.destination=new Node();this.listener=new Node();this.listener.forwardX=new Param();this.listener.forwardY=new Param();this.listener.forwardZ=new Param();this.listener.upX=new Param();this.listener.upY=new Param();this.listener.upZ=new Param();this.nodes=[];this.state="suspended";Context.instances.push(this);}node(){const n=new Node();this.nodes.push(n);return n;}createGain(){return this.node();}createPanner(){return this.node();}createBiquadFilter(){return this.node();}createDynamicsCompressor(){return this.node();}createBufferSource(){return this.node();}createBuffer(channels,length,rate){const data=new Float32Array(length);return {duration:length/rate,getChannelData:()=>data};}resume(){this.state="running";return Promise.resolve();}suspend(){this.state="suspended";return Promise.resolve();}close(){this.state="closed";return Promise.resolve();}}
Context.instances=[];
function frame(audio,time=1,state=[0,2,0,0,0,0,0,0]){return {audio,time,state};}
function rms(data){return Math.sqrt(data.reduce((sum,v)=>sum+v*v,0)/data.length);}
test("all city foley produces bounded non-silent PCM, with distinct engines and timed foot impacts",()=>{
  for(const kind of Audio.KINDS){const data=Audio.synthesize(kind,22050,2.4,1);assert.ok(data.every(Number.isFinite),kind);assert.ok(rms(data)>.001,kind+" is silent");assert.ok(data.every(v=>Math.abs(v)<=.9),kind+" clips");}
  assert.notDeepEqual(Audio.synthesize("car",22050,1,0),Audio.synthesize("truck",22050,1,0));const foot=Audio.synthesize("footsteps",22050,.38,0);assert.ok(rms(foot.subarray(0,1500))>rms(foot.subarray(5500))*4,"shoe impact must decay before the next step");
});
test("a private context starts from the entry gesture, spatial sources fade with distance and listener turns",async()=>{
  const s=new Audio.Sound({Context});assert.equal(s.context,null);await s.start();assert.equal(s.context.state,"running");s.update(frame([{id:"cab",kind:"car",x:0,y:2,z:-3,gain:.5,pitch:1}]));const voice=s.voices.get("cab/car"),near=voice.gain.gain.value;assert.equal(voice.panner.positionZ.value,-3);
  s.update(frame([{id:"cab",kind:"car",x:0,y:2,z:-80,gain:.5,pitch:1}],1.05,[0,2,0,Math.PI/2,0,0,0,0]));assert.ok(voice.gain.gain.value<near*.3);assert.ok(s.context.listener.forwardX.value>.99);assert.equal(Audio.attenuation("car",300),0);s.dispose();
});
test("pause, mute, removal and disposal stop audio and release every source and context",async()=>{
  const s=new Audio.Sound({Context});await s.start();s.update(frame([{id:"bus",kind:"bus",x:1,y:2,z:3,gain:.5,pitch:1,horn:true,doors:true,speed:0}]));const c=s.context;assert.ok(s.voices.size>0&&s.effects.size>0);s.setPaused(true);assert.equal(c.state,"suspended");assert.equal(s.master.gain.value,0);s.setPaused(false);assert.equal(c.state,"running");s.setMuted(true);assert.equal(s.voices.size,0);assert.equal(s.effects.size,0);assert.equal(s.master.gain.value,0);s.setMuted(false);s.update(frame([]));s.dispose();assert.equal(c.state,"closed");assert.ok(c.nodes.every(n=>!n.connected));assert.ok(c.nodes.filter(n=>n.started).every(n=>n.stopped));
});
test("a footfall or ball impact occurs once per movement event, and departed loop voices are removed",async()=>{
  const s=new Audio.Sound({Context});await s.start();const event={id:"walker",kind:"footsteps",x:1,y:1,z:1,gain:.4,oneShot:true,event:7};s.update(frame([event]));const first=s.effects.size;s.update(frame([event]));assert.equal(s.effects.size,first);s.update(frame([{...event,event:8}]));assert.equal(s.effects.size,first+1);s.update(frame([{id:"car",kind:"car",x:1,y:2,z:3}]));assert.equal(s.voices.size,2);s.update(frame([]));assert.equal(s.voices.size,1,"only the local wind loop remains");s.dispose();
});
