# scan-music.ps1
# Scan music/ folder, extract metadata, generate playlist.js
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$musicDir  = Join-Path $scriptDir "..\music"
$output    = Join-Path $musicDir "playlist.js"

$musicDir = [System.IO.Path]::GetFullPath($musicDir)

$exts = @(".mp3", ".flac", ".wav", ".ogg", ".aac", ".m4a", ".wma", ".opus", ".webm", ".aiff")

if (-not (Test-Path $musicDir)) {
    New-Item -ItemType Directory -Path $musicDir -Force | Out-Null
    $empty = 'window.__MUSIC_PLAYLIST = [];'
    [System.IO.File]::WriteAllText($output, $empty, [System.Text.UTF8Encoding]::new($false))
    Write-Host "  music/ folder created, playlist is empty"
    exit 0
}

$audioFiles = Get-ChildItem -Path $musicDir -File | Where-Object { $_.Extension.ToLower() -in $exts } | Sort-Object Name

if ($audioFiles.Count -eq 0) {
    $empty = 'window.__MUSIC_PLAYLIST = [];'
    [System.IO.File]::WriteAllText($output, $empty, [System.Text.UTF8Encoding]::new($false))
    Write-Host "  No audio files found in music/"
    exit 0
}

Write-Host "  Found $($audioFiles.Count) audio file(s), extracting metadata..."

$shell  = New-Object -ComObject Shell.Application
$folder = $shell.Namespace($musicDir)

function Get-MediaProp($folder, $file, $propNames) {
    foreach ($pn in $propNames) {
        for ($i = 0; $i -lt 300; $i++) {
            $name = $folder.GetDetailsOf($null, $i)
            if ($name -eq $pn) {
                $val = $folder.GetDetailsOf($file, $i)
                if ($val) { return $val.Trim() }
                break
            }
        }
    }
    return ""
}

function Find-CoverImage($audioFilePath) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($audioFilePath)
    $dir = [System.IO.Path]::GetDirectoryName($audioFilePath)
    $coverNames = @(
        "$baseName.jpg", "$baseName.png", "$baseName.jpeg",
        "cover.jpg", "cover.png", "cover.jpeg",
        "folder.jpg", "folder.png", "albumart.jpg", "albumart.png",
        "front.jpg", "front.png"
    )
    foreach ($cn in $coverNames) {
        $coverPath = Join-Path $dir $cn
        if (Test-Path $coverPath) {
            try {
                $imgBytes = [System.IO.File]::ReadAllBytes($coverPath)
                $base64 = [Convert]::ToBase64String($imgBytes)
                $ext = [System.IO.Path]::GetExtension($coverPath).ToLower() -replace '\.', ''
                if ($ext -eq 'jpeg') { $ext = 'jpg' }
                $mime = "image/$ext"
                if ($ext -eq 'jpg') { $mime = "image/jpeg" }
                return "data:${mime};base64,${base64}"
            } catch {
                Write-Host "    Warning: cannot read cover $coverPath"
            }
        }
    }
    return ""
}

# Find a default cover for tracks without their own
$defaultCover = ""
foreach ($cn in @("cover.jpg","cover.png","cover.jpeg","folder.jpg","folder.png")) {
    $cp = Join-Path $musicDir $cn
    if (Test-Path $cp) {
        try {
            $imgBytes = [System.IO.File]::ReadAllBytes($cp)
            $base64 = [Convert]::ToBase64String($imgBytes)
            $ext = [System.IO.Path]::GetExtension($cp).ToLower() -replace '\.', ''
            if ($ext -eq 'jpeg') { $ext = 'jpg' }
            $mime = "image/$ext"
            if ($ext -eq 'jpg') { $mime = "image/jpeg" }
            $defaultCover = "data:${mime};base64,${base64}"
            break
        } catch {}
    }
}

$entries = @()
foreach ($f in $audioFiles) {
    $file = $folder.ParseName($f.Name)

    $title = Get-MediaProp $folder $file @("Title","Titel","Titolo","Titre","Titulo")
    if (-not $title) { $title = [System.IO.Path]::GetFileNameWithoutExtension($f.Name) }

    $artist = Get-MediaProp $folder $file @("Contributing artists","Artists","Artist","Kunstler","Artiste","Artista")
    if (-not $artist) { $artist = "Unknown Artist" }

    $album = Get-MediaProp $folder $file @("Album","Album title","Albumtitel")
    if (-not $album) { $album = "" }

    $length = Get-MediaProp $folder $file @("Length","Dauer","Duree","Duracion","Durata")
    if (-not $length) { $length = "" }

    $cover = Find-CoverImage $f.FullName
    if (-not $cover -and $defaultCover) { $cover = $defaultCover }

    $relPath = "./music/$($f.Name)"
    $entry = @"
  {
    file: "$relPath",
    title: "$title",
    artist: "$artist",
    album: "$album",
    duration: "$length",
    cover: "$cover"
  }
"@
    $entries += $entry
    Write-Host "    $title - $artist"
}

$joined = $entries -join ",`n"

$ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$playlistContent = @"
// Auto-generated by scan-music.ps1 at $ts
// Drop music files into music/ then run control.bat or addmusic.bat to update
window.__MUSIC_PLAYLIST = [
$joined
];
"@

[System.IO.File]::WriteAllText($output, $playlistContent, [System.Text.UTF8Encoding]::new($false))
Write-Host "  Generated music/playlist.js ($($audioFiles.Count) track(s))"
